### ISSUE TITLE
Pedido de remoção

### ISSUE THREAD

**Issue by takedownsantana** [serginhovsc/alinevpn#1]
Prezado,

A Apura Cyber Security foi contratada pelo Banco C6 S/A para remover conteúdo que contenha propriedade intelectual da empresa.

Deste modo, solicito, cordialmente, que remova por completo este repositório.

https://github.com/serginhovsc/alinevpn/blob/2efa71c42a2c5cf6c543754a745517ee293b5792/appnovo

Certo de que seremos atendidos, me despeço com votos de elevada estima.

Julius Santana
Advogado
Apura Cybersecurity.

**Comment by serginhovsc** [comment]
ola, iremos fazer a remoção

**Comment by serginhovsc** [comment]
remoção realizada
